In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
import functools

# Loading the Data

In [3]:
fat_supply_csv = "Resources/Fat_Supply_Quantity_Data.csv"
fat_supply_df = pd.read_csv(fat_supply_csv)
fat_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,17.0831,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.0,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,9.2443,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,27.3606,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,0.0,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,22.4638,0.1231,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,0.0,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,14.4436,0.2469,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [4]:
kcal_supply_csv = "Resources/Food_Supply_kcal_Data.csv"
kcal_supply_df = pd.read_csv(kcal_supply_csv)
kcal_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,4.7774,0.8504,0.0,37.1186,0.1501,0.0000,1.4757,1.2006,...,2.3012,0.7504,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.9120,16.0930,1.0591,0.0,16.2107,0.8091,0.1471,3.8982,3.8688,...,2.8244,2.7508,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0896,6.0326,0.1941,0.0,25.0112,0.4181,0.1195,3.1805,1.2543,...,5.7638,2.0457,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,1.9388,4.6927,0.2644,0.0,18.3521,0.0441,0.8372,2.3133,2.9302,...,4.2741,0.3525,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,2.3041,15.3672,1.5429,0.0,13.7215,0.2057,1.7280,3.6824,7.0356,...,4.6904,1.2960,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [5]:
food_quantity_csv = "Resources/Food_Supply_Quantity_kg_Data.csv"
food_quantity_df = pd.read_csv(food_quantity_csv)
food_quantity_df.head()

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0014,0.1973,9.4341,0.0,24.8097,0.2099,0.0350,5.3495,1.2020,...,6.7642,40.5645,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,1.6719,0.1357,18.7684,0.0,5.7817,0.5815,0.2126,6.7861,1.8845,...,11.7753,31.2304,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.2711,0.0282,9.6334,0.0,13.6816,0.5277,0.2416,6.3801,1.1305,...,11.6484,40.3651,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,5.8087,0.0560,4.9278,0.0,9.1085,0.0587,1.7707,6.0005,2.0571,...,2.3041,45.0722,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,3.5764,0.0087,16.6613,0.0,5.9960,0.2274,4.1489,10.7451,5.6888,...,5.4495,33.3233,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [6]:
protein_supply_csv = "Resources/Protein_Supply_Quantity_Data.csv"
protein_supply_df = pd.read_csv(protein_supply_csv)
protein_supply_df.head()

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Miscellaneous,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,9.7523,0.0277,0.0,35.9771,0.4067,0.0647,0.5824,3.1337,...,1.1370,0.0462,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.1840,27.7469,0.0711,0.0,14.2331,1.8069,0.6274,1.2757,7.6582,...,3.2456,0.0544,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0323,13.8360,0.0054,0.0,26.5633,1.2916,0.6350,1.1624,3.5088,...,3.1267,0.1399,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,0.6285,15.2311,0.0277,0.0,20.3882,0.1756,5.4436,1.2754,7.6248,...,0.8133,0.0924,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,0.1535,33.1901,0.1289,0.0,10.5108,0.4850,8.2146,1.2586,16.0670,...,1.6024,0.2947,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

# Transform Dataframes

## Fat Supply Data

In [7]:
# Create a filtered dataframe from specific columns
fat_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
fat_supply_transformed= fat_supply_df[fat_supply_cols].copy()

# Change column names
fat_supply_transformed = fat_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_fat',
                                                    'Cereals - Excluding Beer':'cereals_fat',
                                                    'Eggs':'eggs_fat',
                                                    'Fruits - Excluding Wine': 'fruits_fat',
                                                    'Meat':'meat_fat',
                                                    'Milk - Excluding Butter':'milk_fat',
                                                    'Fish, Seafood': 'fish_seafood_fat', 
                                                    'Vegetables':'vegetables_fat',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
fat_supply_transformed.drop_duplicates("country", inplace=True)
fat_supply_transformed.set_index("country", inplace=True)

fat_supply_transformed

,animal_products_fat,cereals_fat,eggs_fat,fruits_fat,meat_fat,milk_fat,fish_seafood_fat,vegetables_fat,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,21.6397,8.0353,0.6859,0.4246,6.1244,8.2803,0.0327,0.3593,4.5,29.8,0.142134,0.006186,0.123374,38928000.0
Albania,32.0002,2.6734,1.6448,0.6418,8.7428,17.7576,0.1445,0.6503,22.3,6.2,2.967301,0.050951,1.792636,2838000.0
Algeria,14.4175,4.2035,1.2171,0.5772,3.8961,8.0934,0.2008,0.5145,26.6,3.9,0.244897,0.006558,0.167572,44357000.0
Angola,15.3041,6.5545,0.1539,0.3488,11.0268,1.2309,1.4155,0.1231,6.8,25,0.061687,0.001461,0.056808,32522000.0
Antigua and Barbuda,27.7033,3.2153,0.3872,1.2177,14.3202,6.6607,1.5263,0.2469,19.1,NaN,0.293878,0.007143,0.190816,98000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),16.3261,2.5449,0.6555,0.9640,7.0949,5.5217,0.5707,0.1851,25.2,21.2,0.452585,0.004287,0.424399,28645000.0
Vietnam,33.2484,3.7155,0.7839,0.4079,26.4292,0.7520,1.1217,0.6373,2.1,9.3,0.002063,0.000036,0.001526,96209000.0
Yemen,12.5401,11.5271,0.5514,0.2564,8.0010,1.3463,0.3847,0.1667,14.1,38.9,0.007131,0.002062,0.004788,29826000.0
Zambia,9.6005,14.3225,0.6266,0.1343,4.9010,1.2756,1.0070,0.1567,6.5,46.7,0.334133,0.004564,0.290524,18384000.0
Zimbabwe,10.3796,9.7922,0.3682,0.0614,4.5674,2.1040,0.2455,0.0789,12.3,51.3,0.232033,0.008854,0.190964,14863000.0

## Food Supply

In [8]:
# Create a filtered dataframe from specific columns
food_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
food_transformed= food_quantity_df[food_cols].copy()

# Change the column headers/names
food_transformed = food_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_quantity',
                                                    'Cereals - Excluding Beer':'cereals_quantity',
                                                    'Eggs':'eggs_quantity',
                                                    'Fruits - Excluding Wine': 'fruits_quantity',
                                                    'Meat':'meat_quantity',
                                                    'Milk - Excluding Butter':'milk_quantity',
                                                    'Fish, Seafood': 'fish_seafood_quantity', 
                                                    'Vegetables':'vegetables_quantity',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
food_transformed.drop_duplicates("country", inplace=True)
food_transformed.set_index("country", inplace=True)


food_transformed

,animal_products_quantity,cereals_quantity,eggs_quantity,fruits_quantity,meat_quantity,milk_quantity,fish_seafood_quantity,vegetables_quantity,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,9.4341,24.8097,0.2099,5.3495,1.2020,7.5828,0.0350,6.7642,4.5,29.8,0.142134,0.006186,0.123374,38928000.0
Albania,18.7684,5.7817,0.5815,6.7861,1.8845,15.7213,0.2126,11.7753,22.3,6.2,2.967301,0.050951,1.792636,2838000.0
Algeria,9.6334,13.6816,0.5277,6.3801,1.1305,7.6189,0.2416,11.6484,26.6,3.9,0.244897,0.006558,0.167572,44357000.0
Angola,4.9278,9.1085,0.0587,6.0005,2.0571,0.8311,1.7707,2.3041,6.8,25,0.061687,0.001461,0.056808,32522000.0
Antigua and Barbuda,16.6613,5.9960,0.2274,10.7451,5.6888,6.3663,4.1489,5.4495,19.1,NaN,0.293878,0.007143,0.190816,98000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),14.7565,12.9253,0.3389,7.6460,3.8328,9.3920,0.9456,4.1474,25.2,21.2,0.452585,0.004287,0.424399,28645000.0
Vietnam,8.5765,16.8740,0.3077,5.9029,4.4382,0.6069,2.6392,11.9508,2.1,9.3,0.002063,0.000036,0.001526,96209000.0
Yemen,5.7874,27.2077,0.2579,5.1344,2.7871,1.8911,0.5240,3.2135,14.1,38.9,0.007131,0.002062,0.004788,29826000.0
Zambia,6.0197,21.1938,0.3399,1.0183,1.8427,1.7570,1.6924,3.4649,6.5,46.7,0.334133,0.004564,0.290524,18384000.0
Zimbabwe,8.1489,22.6240,0.2678,2.2000,2.6142,4.4310,0.5518,2.3213,12.3,51.3,0.232033,0.008854,0.190964,14863000.0

## KCal Supply

In [9]:
# Create a filtered dataframe from specific columns
kcal_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
kcal_supply_transformed= kcal_supply_df[kcal_supply_cols].copy()

# Rename the column headers
kcal_supply_transformed = kcal_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_kcal',
                                                    'Cereals - Excluding Beer':'cereals_kcal',
                                                    'Eggs':'eggs_kcal',
                                                    'Fruits - Excluding Wine': 'fruits_kcal',
                                                    'Meat':'meat_kcal',
                                                    'Milk - Excluding Butter':'milk_kcal',
                                                    'Fish, Seafood': 'fish_seafood_kcal', 
                                                    'Vegetables':'vegetables_kcal',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
kcal_supply_transformed.drop_duplicates("country", inplace=True)
kcal_supply_transformed.set_index("country", inplace=True)


kcal_supply_transformed

,animal_products_kcal,cereals_kcal,eggs_kcal,fruits_kcal,meat_kcal,milk_kcal,fish_seafood_kcal,vegetables_kcal,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,4.7774,37.1186,0.1501,1.4757,1.2006,2.4512,0.0000,0.7504,4.5,29.8,0.142134,0.006186,0.123374,38928000.0
Albania,16.0930,16.2107,0.8091,3.8982,3.8688,9.9441,0.1471,2.7508,22.3,6.2,2.967301,0.050951,1.792636,2838000.0
Algeria,6.0326,25.0112,0.4181,3.1805,1.2543,3.9869,0.1195,2.0457,26.6,3.9,0.244897,0.006558,0.167572,44357000.0
Angola,4.6927,18.3521,0.0441,2.3133,2.9302,0.5067,0.8372,0.3525,6.8,25,0.061687,0.001461,0.056808,32522000.0
Antigua and Barbuda,15.3672,13.7215,0.2057,3.6824,7.0356,4.6904,1.7280,1.2960,19.1,NaN,0.293878,0.007143,0.190816,98000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),7.2303,21.3126,0.2892,2.3804,3.1368,2.6474,0.4449,0.6674,25.2,21.2,0.452585,0.004287,0.424399,28645000.0
Vietnam,10.9806,26.9833,0.2894,1.8046,7.8311,0.5618,1.0385,1.9578,2.1,9.3,0.002063,0.000036,0.001526,96209000.0
Yemen,3.4667,32.0727,0.1455,1.1879,2.0121,0.6545,0.1697,0.3636,14.1,38.9,0.007131,0.002062,0.004788,29826000.0
Zambia,3.3043,31.5528,0.1988,0.2236,1.5155,0.5217,0.5714,0.4472,6.5,46.7,0.334133,0.004564,0.290524,18384000.0
Zimbabwe,3.9356,29.8044,0.1381,0.4373,1.7491,1.0817,0.1611,0.2532,12.3,51.3,0.232033,0.008854,0.190964,14863000.0

## Protein Supply

In [10]:
# Create a filtered dataframe from specific columns
protein_supply_cols = ["Country", "Animal Products", "Cereals - Excluding Beer", "Eggs", "Fruits - Excluding Wine", \
             "Meat", "Milk - Excluding Butter", "Fish, Seafood", "Vegetables", "Obesity", "Undernourished", "Confirmed", "Deaths", "Recovered", "Population"]

# food_cols = ["Country", "Animal_Products", "Cereals", "Eggs", "Fruits", "Meat", "Milk", "Fish_Seafood", "Vegetables"]
protein_supply_transformed= protein_supply_df[protein_supply_cols].copy()

# Rename the column headers
protein_supply_transformed = protein_supply_transformed.rename(columns={'Country': 'country', 
                                                    'Animal Products':'animal_products_protein',
                                                    'Cereals - Excluding Beer':'cereals_protein',
                                                    'Eggs':'eggs_protein',
                                                    'Fruits - Excluding Wine': 'fruits_protein',
                                                    'Meat':'meat_protein',
                                                    'Milk - Excluding Butter':'milk_protein',
                                                    'Fish, Seafood': 'fish_seafood_protein', 
                                                    'Vegetables':'vegetables_protein',
                                                    'Obesity': 'obesity',
                                                    'Undernourished': 'undernourished',
                                                    'Confirmed': 'confirmed_cases',
                                                    'Deaths': 'deaths',
                                                    'Recovered': 'recovered',
                                                    'Population': 'population'})
# Clean the data by dropping duplicates and setting the index
protein_supply_transformed.drop_duplicates("country", inplace=True)
protein_supply_transformed.set_index("country", inplace=True)

protein_supply_transformed

,animal_products_protein,cereals_protein,eggs_protein,fruits_protein,meat_protein,milk_protein,fish_seafood_protein,vegetables_protein,obesity,undernourished,confirmed_cases,deaths,recovered,population
country,,,,,,,,,,,,,,
Afghanistan,9.7523,35.9771,0.4067,0.5824,3.1337,5.5278,0.0647,1.1370,4.5,29.8,0.142134,0.006186,0.123374,38928000.0
Albania,27.7469,14.2331,1.8069,1.2757,7.6582,16.4750,0.6274,3.2456,22.3,6.2,2.967301,0.050951,1.792636,2838000.0
Algeria,13.8360,26.5633,1.2916,1.1624,3.5088,8.0616,0.6350,3.1267,26.6,3.9,0.244897,0.006558,0.167572,44357000.0
Angola,15.2311,20.3882,0.1756,1.2754,7.6248,1.1460,5.4436,0.8133,6.8,25,0.061687,0.001461,0.056808,32522000.0
Antigua and Barbuda,33.1901,10.5108,0.4850,1.2586,16.0670,7.4349,8.2146,1.6024,19.1,NaN,0.293878,0.007143,0.190816,98000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),22.5411,21.6526,0.8707,1.0662,11.8347,6.3083,2.6477,1.0129,25.2,21.2,0.452585,0.004287,0.424399,28645000.0
Vietnam,20.4466,18.5247,0.7665,0.7165,11.0426,1.0887,5.7435,3.7216,2.1,9.3,0.002063,0.000036,0.001526,96209000.0
Yemen,10.0122,35.1179,0.4320,0.4884,5.9453,1.9630,0.9392,0.5448,14.1,38.9,0.007131,0.002062,0.004788,29826000.0
Zambia,9.8925,28.5182,0.5839,0.0931,4.3158,1.0324,3.0126,0.8039,6.5,46.7,0.334133,0.004564,0.290524,18384000.0
Zimbabwe,11.3443,33.1934,0.5077,0.2636,6.6582,2.4114,1.0837,0.5955,12.3,51.3,0.232033,0.008854,0.190964,14863000.0

# Merge all of the Dataframes into one Dataframe

In [11]:
dfs = [food_transformed, kcal_supply_transformed, fat_supply_transformed, protein_supply_transformed]
nan_value = 0

##EACH DATASET HAS THE SAME DATA IN OBESITY, UNDERNOURISHED, CONFIRMED_CASES, DEATHS, RECOVERED, AND POPULATION

covid_diet = functools.reduce(lambda left, right: pd.merge(left,right,on=['country', 'obesity', 'undernourished', 'confirmed_cases', 'deaths', 'recovered', 'population']), dfs)
covid_diet

,animal_products_quantity,cereals_quantity,eggs_quantity,fruits_quantity,meat_quantity,milk_quantity,fish_seafood_quantity,vegetables_quantity,obesity,undernourished,...,fish_seafood_fat,vegetables_fat,animal_products_protein,cereals_protein,eggs_protein,fruits_protein,meat_protein,milk_protein,fish_seafood_protein,vegetables_protein
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,9.4341,24.8097,0.2099,5.3495,1.2020,7.5828,0.0350,6.7642,4.5,29.8,...,0.0327,0.3593,9.7523,35.9771,0.4067,0.5824,3.1337,5.5278,0.0647,1.1370
Albania,18.7684,5.7817,0.5815,6.7861,1.8845,15.7213,0.2126,11.7753,22.3,6.2,...,0.1445,0.6503,27.7469,14.2331,1.8069,1.2757,7.6582,16.4750,0.6274,3.2456
Algeria,9.6334,13.6816,0.5277,6.3801,1.1305,7.6189,0.2416,11.6484,26.6,3.9,...,0.2008,0.5145,13.8360,26.5633,1.2916,1.1624,3.5088,8.0616,0.6350,3.1267
Angola,4.9278,9.1085,0.0587,6.0005,2.0571,0.8311,1.7707,2.3041,6.8,25,...,1.4155,0.1231,15.2311,20.3882,0.1756,1.2754,7.6248,1.1460,5.4436,0.8133
Antigua and Barbuda,16.6613,5.9960,0.2274,10.7451,5.6888,6.3663,4.1489,5.4495,19.1,NaN,...,1.5263,0.2469,33.1901,10.5108,0.4850,1.2586,16.0670,7.4349,8.2146,1.6024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),14.7565,12.9253,0.3389,7.6460,3.8328,9.3920,0.9456,4.1474,25.2,21.2,...,0.5707,0.1851,22.5411,21.6526,0.8707,1.0662,11.8347,6.3083,2.6477,1.0129
Vietnam,8.5765,16.8740,0.3077,5.9029,4.4382,0.6069,2.6392,11.9508,2.1,9.3,...,1.1217,0.6373,20.4466,18.5247,0.7665,0.7165,11.0426,1.0887,5.7435,3.7216
Yemen,5.7874,27.2077,0.2579,5.1344,2.7871,1.8911,0.5240,3.2135,14.1,38.9,...,0.3847,0.1667,10.0122,35.1179,0.4320,0.4884,5.9453,1.9630,0.9392,0.5448
Zambia,6.0197,21.1938,0.3399,1.0183,1.8427,1.7570,1.6924,3.4649,6.5,46.7,...,1.0070,0.1567,9.8925,28.5182,0.5839,0.0931,4.3158,1.0324,3.0126,0.8039
Zimbabwe,8.1489,22.6240,0.2678,2.2000,2.6142,4.4310,0.5518,2.3213,12.3,51.3,...,0.2455,0.0789,11.3443,33.1934,0.5077,0.2636,6.6582,2.4114,1.0837,0.5955